name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node modules
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build

      - name: Build storybook
        run: yarn lerna run build-storybook

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn typecheck

      - name: Test
        run: yarn test --coverage
