name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node modules
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint --max-warnings=0

      - name: Type check
        run: yarn typecheck

      - name: Test
        run: yarn test --coverage

      - name: Test E2E
        run: yarn test:e2e-ci
        env:
          WAIT_ON_TIMEOUT: 60000 # 60s

      - name: Upload artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: |
            cypress/images
            cypress/videos
          if-no-files-found: ignore
