name: Storybook

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  story-book:
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build dependencies
        run: pnpm exec lerna run build --scope @mocat/interceptor

      - name: Build storybook
        run: pnpm exec lerna run build-storybook
